2021/04/12 20:50:04 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/info
2021/04/12 20:50:04 Http request failed with status: 500
Response body: Unable to write to log.


2021/04/12 20:50:04 Response code 500, retrying after 1 seconds
[2021-04-12T20:50:05.343871] Entering context manager injector.
2021/04/12 20:50:05 Attempt 2 of http call to http://10.0.0.4:16384/sendlogstoartifacts/info
2021/04/12 20:50:05 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['dataprocess.py', '--max_iter', '13'])
Script type = None
[2021-04-12T20:50:06.672788] Entering Run History Context Manager.
[2021-04-12T20:50:07.365010] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-142523/azureml/hd_a6e0455f-cd60-4041-a03f-58d421b4b019_3/mounts/workspaceblobstore/azureml/HD_a6e0455f-cd60-4041-a03f-58d421b4b019_3
[2021-04-12T20:50:07.365281] Preparing to call script [dataprocess.py] with arguments:['--max_iter', '13']
[2021-04-12T20:50:07.365348] After variable expansion, calling script [dataprocess.py] with arguments:['--max_iter', '13']

/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
  age_bins  sex  cp  trestbps      chol  ...  exang  oldpeak  slope  ca  thal
0    62-69    1   3  0.763956 -0.256334  ...      0      2.3      0   0     1
1    29-37    1   2 -0.092738  0.072199  ...      0      3.5      0   0     2
2    38-45    0   1 -0.092738 -0.816773  ...      0      1.4      2   0     2
3    54-61    1   1 -0.663867 -0.198357  ...      0      0.8      2   0     2
4    54-61    0   0 -0.663867  2.082050  ...      1      0.6      2   0     2

[5 rows x 13 columns]
0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64
/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[2021-04-12T20:50:08.287915] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
2 items cleaning up...
2021/04/12 20:50:09 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 1
FilteredData: 0.
Cleanup took 5.503952741622925 seconds
Traceback (most recent call last):
  File "dataprocess.py", line 79, in <module>
    main()
  File "dataprocess.py", line 57, in main
    model = LogisticRegression(max_iter=args.max_iter).fit(x_train, y_train)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 1288, in fit
    accept_large_sparse=solver != 'liblinear')
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/utils/validation.py", line 756, in check_X_y
    estimator=estimator)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/sklearn/utils/validation.py", line 527, in check_array
    array = np.asarray(array, dtype=dtype, order=order)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/pandas/core/generic.py", line 1781, in __array__
    return np.asarray(self._values, dtype=dtype)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '54-61'

[2021-04-12T20:50:13.927023] Finished context manager injector with Exception.
2021/04/12 20:50:14 Could not parse control script error at path: /mnt/batch/tasks/workitems/8623aa86-6b59-40ca-8067-294b67c4cde7/job-1/hd_a6e0455f-cd60-404_3e9123d9-7dcf-404e-b51a-662f3178c7bf/wd/runTaskLetTask_error.json because: File /mnt/batch/tasks/workitems/8623aa86-6b59-40ca-8067-294b67c4cde7/job-1/hd_a6e0455f-cd60-404_3e9123d9-7dcf-404e-b51a-662f3178c7bf/wd/runTaskLetTask_error.json doesn't exist, continuing without
2021/04/12 20:50:14 Failed to run the wrapper cmd with err: exit status 1
2021/04/12 20:50:14 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
2021/04/12 20:50:14 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/04/12 20:50:14 MPI publisher: intel ; version: 2018
2021/04/12 20:50:14 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 2
FilteredData: 0.
2021/04/12 20:50:14 Process Exiting with Code:  1
